export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  smsProviderUrl: process.env.SMS_PROVIDER_URL ?? "",
  smsApiKey: process.env.SMS_PROVIDER_API_KEY ?? "",
  smsAccountSid: process.env.SMS_PROVIDER_ACCOUNT_SID ?? "",
  smsAuthToken: process.env.SMS_PROVIDER_AUTH_TOKEN ?? "",
  smsFromNumber: process.env.SMS_PROVIDER_FROM_NUMBER ?? "",
};
